/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/demo/scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Demo Scenario */
        get: operations["get_demo_scenario_demo_scenario_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Scenario */
        post: operations["create_scenario_scenarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenario */
        get: operations["get_scenario_scenarios__scenario_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}/windows/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Windows */
        post: operations["generate_windows_scenarios__scenario_id__windows_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}/windows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Windows */
        get: operations["get_windows_scenarios__scenario_id__windows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Plan */
        post: operations["create_plan_scenarios__scenario_id__plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get State */
        get: operations["get_state_scenarios__scenario_id__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}/simulation/step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Step Simulation */
        post: operations["step_simulation_scenarios__scenario_id__simulation_step_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Events */
        get: operations["get_events_scenarios__scenario_id__events_get"];
        put?: never;
        /** Inject Event */
        post: operations["inject_event_scenarios__scenario_id__events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}/impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Impact */
        get: operations["get_impact_scenarios__scenario_id__impact_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}/replan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replan */
        post: operations["replan_scenarios__scenario_id__replan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_plans__plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics */
        get: operations["get_metrics_plans__plan_id__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{old_plan_id}/compare/{new_plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare Plans */
        get: operations["compare_plans_plans__old_plan_id__compare__new_plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Traces */
        get: operations["get_traces_plans__plan_id__traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionStatus
         * @enum {string}
         */
        ActionStatus: "planned" | "started" | "completed";
        /** BatteryDropEventRequest */
        BatteryDropEventRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "BATTERY_DROP";
            payload: components["schemas"]["BatteryDropPayloadSchema"];
        };
        /** BatteryDropMissionEventSchema */
        BatteryDropMissionEventSchema: {
            /** Id */
            id: string;
            /** Scenario Id */
            scenario_id: string;
            /**
             * Event Time
             * Format: date-time
             */
            event_time: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "BATTERY_DROP";
            payload: components["schemas"]["BatteryDropPayloadSchema"];
        };
        /** BatteryDropPayloadSchema */
        BatteryDropPayloadSchema: {
            /** Satellite Id */
            satellite_id: string;
            /** New Battery Wh */
            new_battery_wh: number;
        };
        /** CloudBlockEventRequest */
        CloudBlockEventRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "CLOUD_BLOCK";
            payload: components["schemas"]["CloudBlockPayloadSchema"];
        };
        /** CloudBlockMissionEventSchema */
        CloudBlockMissionEventSchema: {
            /** Id */
            id: string;
            /** Scenario Id */
            scenario_id: string;
            /**
             * Event Time
             * Format: date-time
             */
            event_time: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "CLOUD_BLOCK";
            payload: components["schemas"]["CloudBlockPayloadSchema"];
        };
        /** CloudBlockPayloadSchema */
        CloudBlockPayloadSchema: {
            /** Request Id */
            request_id: string;
            /** Window Id */
            window_id: string;
        };
        /** DecisionTraceSchema */
        DecisionTraceSchema: {
            /** Id */
            id: string;
            /** Plan Id */
            plan_id: string;
            /** Event Id */
            event_id: string | null;
            /** Request Id */
            request_id: string | null;
            reason_code: components["schemas"]["ReasonCode"];
            previous_action: components["schemas"]["ScheduledActionSchema"] | null;
            new_action: components["schemas"]["ScheduledActionSchema"] | null;
            /** Constraint Name */
            constraint_name: string | null;
            /** Message */
            message: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** EmergencyTaskEventRequest */
        EmergencyTaskEventRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "EMERGENCY_TASK";
            payload: components["schemas"]["EmergencyTaskPayloadSchema"];
        };
        /** EmergencyTaskMissionEventSchema */
        EmergencyTaskMissionEventSchema: {
            /** Id */
            id: string;
            /** Scenario Id */
            scenario_id: string;
            /**
             * Event Time
             * Format: date-time
             */
            event_time: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "EMERGENCY_TASK";
            payload: components["schemas"]["EmergencyTaskPayloadSchema"];
        };
        /**
         * EmergencyTaskPayloadSchema
         * @description The emergency request and the explicit windows it arrives with.
         */
        EmergencyTaskPayloadSchema: {
            request: components["schemas"]["ObservationRequestSchema"];
            /** Windows */
            windows: components["schemas"]["ObservationWindowSchema"][];
        };
        /** ErrorBody */
        ErrorBody: {
            code: components["schemas"]["ErrorCode"];
            /** Message */
            message: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "INVALID_SCENARIO" | "INVALID_EVENT" | "CONSTRAINT_VIOLATION" | "RESOURCE_NOT_FOUND" | "SIMULATION_STATE_ERROR" | "PLAN_VERSION_CONFLICT";
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        /** ImpactSchema */
        ImpactSchema: {
            /** Id */
            id: string;
            /** Event Id */
            event_id: string;
            /** Evaluated Plan Id */
            evaluated_plan_id: string;
            /** Frozen Action Ids */
            frozen_action_ids: string[];
            /** Valid Unfrozen Action Ids */
            valid_unfrozen_action_ids: string[];
            /** Invalid Unfrozen Action Ids */
            invalid_unfrozen_action_ids: string[];
            /** Reason Codes */
            reason_codes: {
                [key: string]: components["schemas"]["ReasonCode"][];
            };
        };
        /** MetricsSchema */
        MetricsSchema: {
            /** Plan Id */
            plan_id: string;
            /** Mission Utility */
            mission_utility: number;
            /** Completion Rate */
            completion_rate: number;
            /** Violation Count */
            violation_count: number;
            /** Planning Time Ms */
            planning_time_ms: number;
            /** Battery Utilisation */
            battery_utilisation: number;
            /** Storage Utilisation */
            storage_utilisation: number;
            /** Request Pool Size */
            request_pool_size: number;
            /** Request Pool Ids */
            request_pool_ids: string[];
            /** Plan Churn */
            plan_churn: number | null;
            /** Explanation Coverage */
            explanation_coverage: number | null;
        };
        /**
         * MissionEventRequest
         * @description Every event the route accepts, chosen by ``event_type``.
         */
        MissionEventRequest: components["schemas"]["CloudBlockEventRequest"] | components["schemas"]["BatteryDropEventRequest"] | components["schemas"]["EmergencyTaskEventRequest"];
        /**
         * MissionEventSchema
         * @description Every event the log can hold, chosen by ``event_type``.
         */
        MissionEventSchema: components["schemas"]["CloudBlockMissionEventSchema"] | components["schemas"]["BatteryDropMissionEventSchema"] | components["schemas"]["EmergencyTaskMissionEventSchema"];
        /** MissionPlanSchema */
        MissionPlanSchema: {
            /** Id */
            id: string;
            /** Scenario Id */
            scenario_id: string;
            /** Version */
            version: number;
            /** Parent Plan Id */
            parent_plan_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Actions */
            actions: components["schemas"]["ScheduledActionSchema"][];
            /** Unscheduled */
            unscheduled: components["schemas"]["UnscheduledEntrySchema"][];
            /** Mission Utility */
            mission_utility: number;
            /** Violation Count */
            violation_count: number;
            /** Planning Time Ms */
            planning_time_ms: number;
        };
        /** MissionStateSchema */
        MissionStateSchema: {
            /** Scenario Id */
            scenario_id: string;
            /**
             * Simulated Time
             * Format: date-time
             */
            simulated_time: string;
            /** Satellite Id */
            satellite_id: string;
            /** Battery Wh */
            battery_wh: number;
            /** Storage Usage Mb */
            storage_usage_mb: number;
            /** Available */
            available: boolean;
            /** Active Event Ids */
            active_event_ids: string[];
            /** Completed Request Ids */
            completed_request_ids: string[];
            /** Mission Complete */
            mission_complete: boolean;
        };
        /** ObservationRequestSchema */
        ObservationRequestSchema: {
            /** Id */
            id: string;
            /** Target Lat */
            target_lat: number;
            /** Target Lon */
            target_lon: number;
            /** Priority */
            priority: number;
            /** Duration S */
            duration_s: number;
            /**
             * Deadline
             * Format: date-time
             */
            deadline: string;
            /** Energy Cost Wh */
            energy_cost_wh: number;
            /** Storage Cost Mb */
            storage_cost_mb: number;
            /** @default pending */
            status: components["schemas"]["RequestStatus"];
        };
        /** ObservationWindowSchema */
        ObservationWindowSchema: {
            /** Id */
            id: string;
            /** Request Id */
            request_id: string;
            /** Satellite Id */
            satellite_id: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Valid */
            valid: boolean;
            /** Invalid Reason */
            invalid_reason: string | null;
        };
        /**
         * PlanChangeType
         * @enum {string}
         */
        PlanChangeType: "UNCHANGED" | "MOVED" | "INSERTED" | "DROPPED" | "COMPLETED";
        /** PlanDiffEntrySchema */
        PlanDiffEntrySchema: {
            /** Request Id */
            request_id: string;
            change_type: components["schemas"]["PlanChangeType"];
            reason_code: components["schemas"]["ReasonCode"];
            /** Old Start */
            old_start: string | null;
            /** New Start */
            new_start: string | null;
        };
        /** PlanDiffSchema */
        PlanDiffSchema: {
            /** From Plan Id */
            from_plan_id: string;
            /** To Plan Id */
            to_plan_id: string;
            /** Entries */
            entries: components["schemas"]["PlanDiffEntrySchema"][];
            metrics_before?: components["schemas"]["MetricsSchema"] | null;
            metrics_after?: components["schemas"]["MetricsSchema"] | null;
            /**
             * Request Pool Mismatch
             * @default false
             */
            request_pool_mismatch: boolean;
        };
        /**
         * ReasonCode
         * @enum {string}
         */
        ReasonCode: "WINDOW_INVALIDATED" | "INSUFFICIENT_BATTERY" | "INSUFFICIENT_STORAGE" | "DEADLINE_VIOLATION" | "TIME_OVERLAP" | "SATELLITE_UNAVAILABLE" | "DISPLACED_BY_COMPETING_REQUEST" | "ALTERNATIVE_WINDOW_AVAILABLE" | "NO_ALTERNATIVE_WINDOW" | "REQUEST_UNCHANGED";
        /** ReplanRequest */
        ReplanRequest: {
            /** Expected Parent Plan Id */
            expected_parent_plan_id: string;
        };
        /**
         * RequestStatus
         * @enum {string}
         */
        RequestStatus: "pending" | "scheduled" | "completed" | "dropped" | "expired";
        /** SatelliteSchema */
        SatelliteSchema: {
            /** Id */
            id: string;
            /** Battery Capacity Wh */
            battery_capacity_wh: number;
            /** Battery Charge Wh */
            battery_charge_wh: number;
            /** Storage Capacity Mb */
            storage_capacity_mb: number;
            /** Storage Usage Mb */
            storage_usage_mb: number;
            /**
             * Available
             * @default true
             */
            available: boolean;
        };
        /** ScenarioSchema */
        ScenarioSchema: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
            satellite: components["schemas"]["SatelliteSchema"];
            /** Requests */
            requests: components["schemas"]["ObservationRequestSchema"][];
        };
        /** ScheduledActionSchema */
        ScheduledActionSchema: {
            /** Id */
            id: string;
            /** Request Id */
            request_id: string;
            /** Satellite Id */
            satellite_id: string;
            /** Window Id */
            window_id: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Energy Cost Wh */
            energy_cost_wh: number;
            /** Storage Cost Mb */
            storage_cost_mb: number;
            status: components["schemas"]["ActionStatus"];
        };
        /** StepRequest */
        StepRequest: {
            /** Seconds */
            seconds: number;
        };
        /** UnscheduledEntrySchema */
        UnscheduledEntrySchema: {
            /** Request Id */
            request_id: string;
            reason_code: components["schemas"]["ReasonCode"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_demo_scenario_demo_scenario_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioSchema"];
                };
            };
        };
    };
    create_scenario_scenarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioSchema"];
                };
            };
            /** @description Invalid scenario or event */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_scenario_scenarios__scenario_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioSchema"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    generate_windows_scenarios__scenario_id__windows_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationWindowSchema"][];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_windows_scenarios__scenario_id__windows_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationWindowSchema"][];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_plan_scenarios__scenario_id__plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionPlanSchema"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Mission state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_state_scenarios__scenario_id__state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionStateSchema"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    step_simulation_scenarios__scenario_id__simulation_step_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionStateSchema"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Mission state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_events_scenarios__scenario_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionEventSchema"][];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    inject_event_scenarios__scenario_id__events_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MissionEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionEventSchema"];
                };
            };
            /** @description Invalid scenario or event */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Mission state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_impact_scenarios__scenario_id__impact_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImpactSchema"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Mission state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    replan_scenarios__scenario_id__replan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionPlanSchema"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Mission state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_plan_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionPlanSchema"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_metrics_plans__plan_id__metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsSchema"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    compare_plans_plans__old_plan_id__compare__new_plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                old_plan_id: string;
                new_plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDiffSchema"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_traces_plans__plan_id__traces_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionTraceSchema"][];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
