/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/demo/scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Demo Scenario */
        get: operations["get_demo_scenario_demo_scenario_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Examples */
        get: operations["list_examples_examples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/examples/{example_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Example */
        get: operations["get_example_examples__example_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ground-stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ground Stations */
        get: operations["list_ground_stations_ground_stations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Contacts
         * @description Contact windows at the mission's stations, communication outages applied.
         */
        get: operations["get_contacts_scenarios__scenario_id__contacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orbital-elements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Elements */
        get: operations["list_elements_orbital_elements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orbital-elements/{norad_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Elements */
        get: operations["get_elements_orbital_elements__norad_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orbital-elements/parse-tle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Tle */
        post: operations["parse_tle_orbital_elements_parse_tle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Scenario */
        post: operations["validate_scenario_scenarios_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_scenarios_get"];
        put?: never;
        /** Create Scenario */
        post: operations["create_scenario_scenarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenario */
        get: operations["get_scenario_scenarios__scenario_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plans */
        get: operations["list_plans_scenarios__scenario_id__plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}/ground-track": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ground Track */
        get: operations["get_ground_track_scenarios__scenario_id__ground_track_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Requests */
        get: operations["get_requests_scenarios__scenario_id__requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}/windows/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Windows */
        post: operations["generate_windows_scenarios__scenario_id__windows_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}/windows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Windows */
        get: operations["get_windows_scenarios__scenario_id__windows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Plan */
        post: operations["create_plan_scenarios__scenario_id__plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get State */
        get: operations["get_state_scenarios__scenario_id__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}/simulation/step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Step Simulation */
        post: operations["step_simulation_scenarios__scenario_id__simulation_step_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Events */
        get: operations["get_events_scenarios__scenario_id__events_get"];
        put?: never;
        /** Inject Event */
        post: operations["inject_event_scenarios__scenario_id__events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}/impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Impact */
        get: operations["get_impact_scenarios__scenario_id__impact_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}/replan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replan */
        post: operations["replan_scenarios__scenario_id__replan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_plans__plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics */
        get: operations["get_metrics_plans__plan_id__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{old_plan_id}/compare/{new_plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare Plans */
        get: operations["compare_plans_plans__old_plan_id__compare__new_plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Traces */
        get: operations["get_traces_plans__plan_id__traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionKind
         * @enum {string}
         */
        ActionKind: "imaging" | "downlink";
        /**
         * ActionStatus
         * @enum {string}
         */
        ActionStatus: "planned" | "started" | "completed";
        /** BatteryDropEventRequest */
        BatteryDropEventRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "BATTERY_DROP";
            payload: components["schemas"]["BatteryDropPayloadSchema"];
        };
        /** BatteryDropMissionEventSchema */
        BatteryDropMissionEventSchema: {
            /** Id */
            id: string;
            /** Scenario Id */
            scenario_id: string;
            /**
             * Event Time
             * Format: date-time
             */
            event_time: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "BATTERY_DROP";
            payload: components["schemas"]["BatteryDropPayloadSchema"];
        };
        /** BatteryDropPayloadSchema */
        BatteryDropPayloadSchema: {
            /** Satellite Id */
            satellite_id: string;
            /** New Battery Wh */
            new_battery_wh: number;
        };
        /** CloudBlockEventRequest */
        CloudBlockEventRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "CLOUD_BLOCK";
            payload: components["schemas"]["CloudBlockPayloadSchema"];
        };
        /** CloudBlockMissionEventSchema */
        CloudBlockMissionEventSchema: {
            /** Id */
            id: string;
            /** Scenario Id */
            scenario_id: string;
            /**
             * Event Time
             * Format: date-time
             */
            event_time: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "CLOUD_BLOCK";
            payload: components["schemas"]["CloudBlockPayloadSchema"];
        };
        /** CloudBlockPayloadSchema */
        CloudBlockPayloadSchema: {
            /** Request Id */
            request_id: string;
            /** Window Id */
            window_id: string;
            /** Source */
            source?: string | null;
            /** Cloud Cover Pct */
            cloud_cover_pct?: number | null;
            /** Threshold Pct */
            threshold_pct?: number | null;
        };
        /** CommunicationOutageEventRequest */
        CommunicationOutageEventRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "COMMUNICATION_OUTAGE";
            payload: components["schemas"]["CommunicationOutagePayloadSchema"];
        };
        /** CommunicationOutageMissionEventSchema */
        CommunicationOutageMissionEventSchema: {
            /** Id */
            id: string;
            /** Scenario Id */
            scenario_id: string;
            /**
             * Event Time
             * Format: date-time
             */
            event_time: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "COMMUNICATION_OUTAGE";
            payload: components["schemas"]["CommunicationOutagePayloadSchema"];
        };
        /** CommunicationOutagePayloadSchema */
        CommunicationOutagePayloadSchema: {
            /** Station Id */
            station_id: string;
            /**
             * Outage Start
             * Format: date-time
             */
            outage_start: string;
            /**
             * Outage End
             * Format: date-time
             */
            outage_end: string;
        };
        /** ContactWindowSchema */
        ContactWindowSchema: {
            /** Id */
            id: string;
            /** Station Id */
            station_id: string;
            /** Satellite Id */
            satellite_id: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Peak Elevation Deg */
            peak_elevation_deg: number;
            /**
             * Peak Time
             * Format: date-time
             */
            peak_time: string;
            /** Valid */
            valid: boolean;
            /** Invalid Reason */
            invalid_reason?: string | null;
            /** Source */
            source?: string | null;
        };
        /** DecisionTraceSchema */
        DecisionTraceSchema: {
            /** Id */
            id: string;
            /** Plan Id */
            plan_id: string;
            /** Event Id */
            event_id: string | null;
            /** Request Id */
            request_id: string | null;
            reason_code: components["schemas"]["ReasonCode"];
            previous_action: components["schemas"]["ScheduledActionSchema"] | null;
            new_action: components["schemas"]["ScheduledActionSchema"] | null;
            /** Constraint Name */
            constraint_name: string | null;
            /** Message */
            message: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** EmergencyTaskEventRequest */
        EmergencyTaskEventRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "EMERGENCY_TASK";
            payload: components["schemas"]["EmergencyTaskPayloadSchema"];
        };
        /** EmergencyTaskMissionEventSchema */
        EmergencyTaskMissionEventSchema: {
            /** Id */
            id: string;
            /** Scenario Id */
            scenario_id: string;
            /**
             * Event Time
             * Format: date-time
             */
            event_time: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "EMERGENCY_TASK";
            payload: components["schemas"]["EmergencyTaskPayloadSchema"];
        };
        /**
         * EmergencyTaskPayloadSchema
         * @description The emergency request and the explicit windows it arrives with.
         *
         *     A cue arrival (ADR-0015) also carries ``source``, ``source_event_id``
         *     and ``alert_level`` together, with optional ``mag`` and ``sig``.
         */
        EmergencyTaskPayloadSchema: {
            request: components["schemas"]["ObservationRequestSchema"];
            /** Windows */
            windows?: components["schemas"]["ObservationWindowSchema"][] | null;
            /** Source */
            source?: string | null;
            /** Source Event Id */
            source_event_id?: string | null;
            /** Alert Level */
            alert_level?: ("red" | "orange" | "yellow" | "green" | "unknown") | null;
            /** Mag */
            mag?: number | null;
            /** Sig */
            sig?: number | null;
        };
        /** ErrorBody */
        ErrorBody: {
            code: components["schemas"]["ErrorCode"];
            /** Message */
            message: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "INVALID_SCENARIO" | "INVALID_EVENT" | "CONSTRAINT_VIOLATION" | "RESOURCE_NOT_FOUND" | "SIMULATION_STATE_ERROR" | "PLAN_VERSION_CONFLICT";
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        /** GroundStationSchema */
        GroundStationSchema: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Altitude M */
            altitude_m: number;
            /** Min Elevation Deg */
            min_elevation_deg: number;
        };
        /** GroundTrackPointSchema */
        GroundTrackPointSchema: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Altitude Km */
            altitude_km: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImpactSchema */
        ImpactSchema: {
            /** Id */
            id: string;
            /** Event Id */
            event_id: string;
            /** Evaluated Plan Id */
            evaluated_plan_id: string;
            /** Frozen Action Ids */
            frozen_action_ids: string[];
            /** Valid Unfrozen Action Ids */
            valid_unfrozen_action_ids: string[];
            /** Invalid Unfrozen Action Ids */
            invalid_unfrozen_action_ids: string[];
            /** Reason Codes */
            reason_codes: {
                [key: string]: components["schemas"]["ReasonCode"][];
            };
        };
        /** MetricsSchema */
        MetricsSchema: {
            /** Plan Id */
            plan_id: string;
            /** Mission Utility */
            mission_utility: number;
            /** Completion Rate */
            completion_rate: number;
            /** Violation Count */
            violation_count: number;
            /** Planning Time Ms */
            planning_time_ms: number;
            /** Battery Utilisation */
            battery_utilisation: number;
            /** Storage Utilisation */
            storage_utilisation: number;
            /** Request Pool Size */
            request_pool_size: number;
            /** Request Pool Ids */
            request_pool_ids: string[];
            /**
             * Measured At
             * Format: date-time
             */
            measured_at: string;
            /** Plan Churn */
            plan_churn: number | null;
            /** Explanation Coverage */
            explanation_coverage: number | null;
            /**
             * Downlink Action Count
             * @default 0
             */
            downlink_action_count: number;
            /**
             * Downlink Volume Mb
             * @default 0
             */
            downlink_volume_mb: number;
        };
        /**
         * MissionEventRequest
         * @description Every event the route accepts, chosen by ``event_type``.
         */
        MissionEventRequest: components["schemas"]["CloudBlockEventRequest"] | components["schemas"]["BatteryDropEventRequest"] | components["schemas"]["EmergencyTaskEventRequest"] | components["schemas"]["SatelliteOutageEventRequest"] | components["schemas"]["CommunicationOutageEventRequest"];
        /**
         * MissionEventSchema
         * @description Every event the log can hold, chosen by ``event_type``.
         */
        MissionEventSchema: components["schemas"]["CloudBlockMissionEventSchema"] | components["schemas"]["BatteryDropMissionEventSchema"] | components["schemas"]["EmergencyTaskMissionEventSchema"] | components["schemas"]["SatelliteOutageMissionEventSchema"] | components["schemas"]["CommunicationOutageMissionEventSchema"];
        /** MissionPlanSchema */
        MissionPlanSchema: {
            /**
             * Planner Name
             * @default greedy
             */
            planner_name: string;
            /** Solver Details */
            solver_details?: {
                [key: string]: unknown;
            } | null;
            /** Id */
            id: string;
            /** Scenario Id */
            scenario_id: string;
            /** Version */
            version: number;
            /** Parent Plan Id */
            parent_plan_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Actions */
            actions: components["schemas"]["ScheduledActionSchema"][];
            /** Unscheduled */
            unscheduled: components["schemas"]["UnscheduledEntrySchema"][];
            /** Mission Utility */
            mission_utility: number;
            /** Violation Count */
            violation_count: number;
            /** Planning Time Ms */
            planning_time_ms: number;
        };
        /** MissionStateSchema */
        MissionStateSchema: {
            /** Scenario Id */
            scenario_id: string;
            /**
             * Simulated Time
             * Format: date-time
             */
            simulated_time: string;
            /** Satellite Id */
            satellite_id: string;
            /** Battery Wh */
            battery_wh: number;
            /** Storage Usage Mb */
            storage_usage_mb: number;
            /** Available */
            available: boolean;
            /** Active Event Ids */
            active_event_ids: string[];
            /** Completed Request Ids */
            completed_request_ids: string[];
            /** Mission Complete */
            mission_complete: boolean;
        };
        /** ObservationRequestSchema */
        ObservationRequestSchema: {
            /** Id */
            id: string;
            /** Target Lat */
            target_lat: number;
            /** Target Lon */
            target_lon: number;
            /** Priority */
            priority: number;
            /** Duration S */
            duration_s: number;
            /**
             * Deadline
             * Format: date-time
             */
            deadline: string;
            /** Energy Cost Wh */
            energy_cost_wh: number;
            /** Storage Cost Mb */
            storage_cost_mb: number;
            /** @default pending */
            status: components["schemas"]["RequestStatus"];
            /** Target Name */
            target_name?: string | null;
        };
        /** ObservationWindowSchema */
        ObservationWindowSchema: {
            /** Id */
            id: string;
            /** Request Id */
            request_id: string;
            /** Satellite Id */
            satellite_id: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Valid */
            valid: boolean;
            /** Invalid Reason */
            invalid_reason: string | null;
            /** Peak Elevation Deg */
            peak_elevation_deg?: number | null;
            /** Peak Time */
            peak_time?: string | null;
            /** Min Off Nadir Deg */
            min_off_nadir_deg?: number | null;
            /** Sun Elevation Deg */
            sun_elevation_deg?: number | null;
            /** Source */
            source?: string | null;
        };
        /** OrbitalElementsSchema */
        OrbitalElementsSchema: {
            /** Norad Id */
            norad_id: number;
            /** Name */
            name: string;
            /** International Designator */
            international_designator: string;
            /**
             * Epoch
             * Format: date-time
             */
            epoch: string;
            /** Omm */
            omm: {
                [key: string]: unknown;
            };
            /** Source */
            source: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Sha256 */
            sha256: string;
            /** Tle Line1 */
            tle_line1?: string | null;
            /** Tle Line2 */
            tle_line2?: string | null;
        };
        /**
         * PlanChangeType
         * @enum {string}
         */
        PlanChangeType: "UNCHANGED" | "MOVED" | "INSERTED" | "DROPPED" | "COMPLETED";
        /** PlanDiffEntrySchema */
        PlanDiffEntrySchema: {
            /** Request Id */
            request_id: string;
            change_type: components["schemas"]["PlanChangeType"];
            reason_code: components["schemas"]["ReasonCode"];
            /** Old Start */
            old_start: string | null;
            /** New Start */
            new_start: string | null;
        };
        /** PlanDiffSchema */
        PlanDiffSchema: {
            /** From Plan Id */
            from_plan_id: string;
            /** To Plan Id */
            to_plan_id: string;
            /** Entries */
            entries: components["schemas"]["PlanDiffEntrySchema"][];
            metrics_before?: components["schemas"]["MetricsSchema"] | null;
            metrics_after?: components["schemas"]["MetricsSchema"] | null;
            /**
             * Request Pool Mismatch
             * @default false
             */
            request_pool_mismatch: boolean;
        };
        /**
         * ReasonCode
         * @enum {string}
         */
        ReasonCode: "WINDOW_INVALIDATED" | "INSUFFICIENT_BATTERY" | "INSUFFICIENT_STORAGE" | "DEADLINE_VIOLATION" | "TIME_OVERLAP" | "SATELLITE_UNAVAILABLE" | "DISPLACED_BY_COMPETING_REQUEST" | "ALTERNATIVE_WINDOW_AVAILABLE" | "NO_ALTERNATIVE_WINDOW" | "NO_OBSERVATION_WINDOW" | "REQUEST_UNCHANGED" | "HIGHER_PRIORITY_TASK_INSERTED";
        /** ReplanRequest */
        ReplanRequest: {
            /** Planner */
            planner?: ("greedy" | "cp_sat") | null;
            /** Expected Parent Plan Id */
            expected_parent_plan_id: string;
        };
        /**
         * RequestStatus
         * @enum {string}
         */
        RequestStatus: "pending" | "scheduled" | "completed" | "dropped" | "expired";
        /** SatelliteOutageEventRequest */
        SatelliteOutageEventRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "SATELLITE_UNAVAILABLE";
            payload: components["schemas"]["SatelliteOutagePayloadSchema"];
        };
        /** SatelliteOutageMissionEventSchema */
        SatelliteOutageMissionEventSchema: {
            /** Id */
            id: string;
            /** Scenario Id */
            scenario_id: string;
            /**
             * Event Time
             * Format: date-time
             */
            event_time: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "SATELLITE_UNAVAILABLE";
            payload: components["schemas"]["SatelliteOutagePayloadSchema"];
        };
        /** SatelliteOutagePayloadSchema */
        SatelliteOutagePayloadSchema: {
            /** Satellite Id */
            satellite_id: string;
            /**
             * Outage Start
             * Format: date-time
             */
            outage_start: string;
            /**
             * Outage End
             * Format: date-time
             */
            outage_end: string;
        };
        /** SatelliteSchema */
        SatelliteSchema: {
            /** Id */
            id: string;
            /** Battery Capacity Wh */
            battery_capacity_wh: number;
            /** Battery Charge Wh */
            battery_charge_wh: number;
            /** Storage Capacity Mb */
            storage_capacity_mb: number;
            /** Storage Usage Mb */
            storage_usage_mb: number;
            /**
             * Available
             * @default true
             */
            available: boolean;
            orbit?: components["schemas"]["OrbitalElementsSchema"] | null;
        };
        /** ScenarioPreviewSchema */
        ScenarioPreviewSchema: {
            /** Errors */
            errors: string[];
            /** Warnings */
            warnings: string[];
            /** Windows */
            windows: components["schemas"]["ObservationWindowSchema"][];
            /** Window Counts */
            window_counts: {
                [key: string]: number;
            };
            /**
             * Ground Track
             * @default []
             */
            ground_track: components["schemas"]["GroundTrackPointSchema"][];
        };
        /** ScenarioSchema */
        ScenarioSchema: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
            satellite: components["schemas"]["SatelliteSchema"];
            /** Requests */
            requests: components["schemas"]["ObservationRequestSchema"][];
            window_policy?: components["schemas"]["WindowPolicySchema"] | null;
        };
        /** ScenarioSummarySchema */
        ScenarioSummarySchema: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
            /** Provider */
            provider: string;
        };
        /** ScheduledActionSchema */
        ScheduledActionSchema: {
            /** Id */
            id: string;
            /** Request Id */
            request_id: string | null;
            /** Satellite Id */
            satellite_id: string;
            /** Window Id */
            window_id: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Energy Cost Wh */
            energy_cost_wh: number;
            /** Storage Cost Mb */
            storage_cost_mb: number;
            status: components["schemas"]["ActionStatus"];
            /** @default imaging */
            kind: components["schemas"]["ActionKind"];
            /** Station Id */
            station_id?: string | null;
        };
        /** StepRequest */
        StepRequest: {
            /** Seconds */
            seconds: number;
        };
        /** TleParseRequest */
        TleParseRequest: {
            /** Name */
            name: string;
            /** Line1 */
            line1: string;
            /** Line2 */
            line2: string;
        };
        /** UnscheduledEntrySchema */
        UnscheduledEntrySchema: {
            /** Request Id */
            request_id: string;
            reason_code: components["schemas"]["ReasonCode"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WindowPolicySchema */
        WindowPolicySchema: {
            /**
             * Provider
             * @enum {string}
             */
            provider: "synthetic" | "canonical_demo" | "orbital";
            /**
             * Max Off Nadir Deg
             * @default 30
             */
            max_off_nadir_deg: number;
            /**
             * Min Sun Elevation Deg
             * @default 10
             */
            min_sun_elevation_deg: number | null;
            /**
             * Settling Time S
             * @default 0
             */
            settling_time_s: number;
            /**
             * Culmination Placement
             * @default false
             */
            culmination_placement: boolean;
            /** Ground Station Ids */
            ground_station_ids?: string[];
            /**
             * Downlink Rate Mb S
             * @default 0
             */
            downlink_rate_mb_s: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_demo_scenario_demo_scenario_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioSchema"];
                };
            };
        };
    };
    list_examples_examples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioSummarySchema"][];
                };
            };
        };
    };
    get_example_examples__example_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                example_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ground_stations_ground_stations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroundStationSchema"][];
                };
            };
        };
    };
    get_contacts_scenarios__scenario_id__contacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactWindowSchema"][];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_elements_orbital_elements_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrbitalElementsSchema"][];
                };
            };
        };
    };
    get_elements_orbital_elements__norad_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                norad_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrbitalElementsSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_tle_orbital_elements_parse_tle_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TleParseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrbitalElementsSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_scenario_scenarios_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioPreviewSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioSummarySchema"][];
                };
            };
        };
    };
    create_scenario_scenarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioSchema"];
                };
            };
            /** @description Invalid scenario or event */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_scenario_scenarios__scenario_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioSchema"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_plans_scenarios__scenario_id__plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionPlanSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ground_track_scenarios__scenario_id__ground_track_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                step_s?: number;
            };
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroundTrackPointSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_requests_scenarios__scenario_id__requests_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationRequestSchema"][];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    generate_windows_scenarios__scenario_id__windows_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationWindowSchema"][];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_windows_scenarios__scenario_id__windows_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationWindowSchema"][];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_plan_scenarios__scenario_id__plan_post: {
        parameters: {
            query?: {
                planner?: "greedy" | "cp_sat";
            };
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionPlanSchema"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Mission state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_state_scenarios__scenario_id__state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionStateSchema"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    step_simulation_scenarios__scenario_id__simulation_step_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionStateSchema"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Mission state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_events_scenarios__scenario_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionEventSchema"][];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    inject_event_scenarios__scenario_id__events_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MissionEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionEventSchema"];
                };
            };
            /** @description Invalid scenario or event */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Mission state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_impact_scenarios__scenario_id__impact_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImpactSchema"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Mission state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    replan_scenarios__scenario_id__replan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionPlanSchema"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Mission state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_plan_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionPlanSchema"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_metrics_plans__plan_id__metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsSchema"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    compare_plans_plans__old_plan_id__compare__new_plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                old_plan_id: string;
                new_plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDiffSchema"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_traces_plans__plan_id__traces_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionTraceSchema"][];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
